title: Biografía
theme: minima
author: David Esteban Gil Rodríguez
email: daegilro@unal.edu.co
description: > # this means to ignore newlines until "baseurl:"
  Pagina de prueba, para aprender a diseñarla y quede bien aspera

# social links
instagram_username: aunsinnombre # DO NOT include the @ character, or else the build will fail!
github_username:  daegilro # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
